# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixel/gsans/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixel/gsans/common

PRODUCT_COPY_FILES += \
    vendor/pixel/gsans/common/proprietary/product/etc/fonts_customization.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/fonts_customization.xml \
    vendor/pixel/gsans/common/proprietary/product/fonts/GoogleSans-Italic.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/GoogleSans-Italic.ttf \
    vendor/pixel/gsans/common/proprietary/product/fonts/GoogleSans-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/GoogleSans-Regular.ttf \
    vendor/pixel/gsans/common/proprietary/product/fonts/GoogleSansClock-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/GoogleSansClock-Regular.ttf \
    vendor/pixel/gsans/common/proprietary/product/fonts/GoogleSansFlex-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/GoogleSansFlex-Regular.ttf \
    vendor/pixel/gsans/common/proprietary/product/fonts/GoogleSansFlexClock-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/GoogleSansFlexClock-Regular.ttf
